zip:
  url           : https://www.post.japanpost.jp/zipcode/dl/kogaki/zip/ken_all.zip
  file          : ken_all.zip
  workingDir    : /tmp/jp_postcode/
  baseEncording : Shift_JIS

csv:
  file       : KEN_ALL.CSV
  outputFile : output.csv
  workingDir : /tmp/jp_postcode/
  header:
    - jisX0402
    - postcode5
    - postcode7
    - state_kana
    - city_kana
    - street_kana
    - state
    - city
    - street
    - flg_multiple_postcode
    - flg_include_ban
    - flg_include_chome
    - flg_multiple_address
    - flg_changed
    - flg_why_changed
